### PR TITLE
VEN-406 | revise directory structure

### PR DESCRIPTION
**Pull request by Zeukkari**
This admin UI is split into distinct categories and each category contains three views:
- row
- extended row
- full page view

This PR tries to group the views together per category.

## Additional tinkering

- filler icons for side menu
- "logout"
- rename interfaces consistently
- remove duplicate loading indicators
- add loading indicators to individual customer/harbor pages

### CODE REVIEW

**Comment by Zeukkari** [comment]
The main point of this pull request is to reorganize source directory so that domain-specific source files are grouped together. We will probably discard this since it's difficult to maintain.

**Comment by Zeukkari** [comment]
Zeukkari

**Comment by Zeukkari** [comment]
@Zeukkari

**Comment by Zeukkari** [comment]
@Zeukkari

**Comment by Zeukkari** [comment]
@Zeukkari

**Comment by Nizar-Rahme** [comment]
For some reason, Travis is still pending 🤔
Can you update the branch?

**Comment by Zeukkari** [comment]
closing this to reduce maintenance

**Pull request closed without merging**
