### PR TITLE
VEN-952 | Add missing env variables for gitlab pipeline

### PR DESCRIPTION
**Pull request by Nizar-Rahme**
## Description :sparkles:
- Update GitLab and Docker config files to reflect the new changes of env variables

### Related :handshake:
[VEN-952](https://helsinkisolutionoffice.atlassian.net/browse/VEN-952): FE: Add recurring invoicing page

### CODE REVIEW

**Review by ahie — APPROVED** [review]

**Comment by ahie** [comment]
Looks like the browser tests are missing these variables also

**Comment by Nizar-Rahme** [comment]
I am wondering why! Browser tests should read them from .env file, they passed in the previous PR 🤔

**Comment by Nizar-Rahme** [comment]
Even [this step](https://gitlab.com/City-of-Helsinki/KuVa/github-mirrors/berth-reservations-admin/-/jobs/896906284) is failing on GitLab, any insights?

**Comment by ahie** [comment]
That just looks like a random failure to me:
> Error from server (BadRequest): container "anders-deploy-app" in pod "qa-r-fix-missing-m82ea6-review-6bf7d94dc4-d876m" is waiting to start: trying and failing to pull image

**Comment by ahie** [comment]
Are GHA browser tests using `TEST_ENV_URL` or `LOCAL_ENV_URL`? Looks like they're using `TEST_ENV_URL` for which the login is broken before this fix.

**Comment by ahie** [comment]
So the fix would be to change `getEnvUrl` in `browser-tests/utils/settings.ts` to always return localhost. Otherwise PRs that add new browsertests for new features in the same PR will also be broken. I think the `TEST_ENV_URL` is an artifact from before GHA when travis only ran them as a cron job.

**Comment by Nizar-Rahme** [comment]
Let's try that! 👍

**Comment by Nizar-Rahme** [comment]
But in this case, don't we need to run a local instance in order to run the browser tests?

**Comment by ahie** [comment]
Yes that would also need to be done

**Comment by ahie** [comment]
But I don't see any other option to getting the browser tests to work correctly for PRs.

**Pull request merged**
