### PR TITLE
VEN-1340: Winter storage area edit

### PR DESCRIPTION
**Pull request by melniiv**
## Description :sparkles:
Adds the edit form and edit button to the individual winter storage area

## Screenshots :camera_flash:
image

### CODE REVIEW

**Review by nikomakela — COMMENTED** [review]
I don't think the WWW-URL should be a mandatory field. Other than that OK! Code changes looks good.

**Comment by nikomakela** [comment]
> I don't think the WWW-URL should be a mandatory field. Other than that OK! Code changes looks good.

Should it also be visible some where. Cannot find it from the UI.

**Comment by melniiv** [comment]
its not for some reason in the card, i was also wondering why, but we can add it later if there is a need

**Review by nikomakela — APPROVED** [review]
approved, but the url should not be required!

**Pull request merged**
