### PR TITLE
VEN-898 | Persist list view tables' sorting and filtering states

### PR DESCRIPTION
**Pull request by ahie**
## Description :sparkles:

Sorting and filtering options are persisted for each list view even after navigating to and from their respective pages.

Additionally implements a new type of filter for application pages, which enables filtering by application status.

### Closes :no_good_woman:

[VEN-898](https://helsinkisolutionoffice.atlassian.net/browse/VEN-898)

### Automated tests :gear:️

- `browser-tests/listViewTableStatePersistence.ts`
- Updated relevant unit tests

### Manual testing :construction_worker_man:

Persistent table states:

1. Go to any of the listing pages:
    - ApplicationList
    - CustomerList
    - HarborList
    - UnmarkedWsNoticeList
    - WinterStorageApplicationList
    - WinterStorageAreaList
2. Change column sorting and or any additional filters the page might have
3. Navigate away from the page
4. When returning to the page, any settings changed in step 4. should still be present

Filtering by application status:

1. Go to any application page:
    - ApplicationList
    - UnmarkedWsNoticeList
    - WinterStorageApplicationList
2. Change the filter in the top right corner of the table
4. Only applications in the selected state should be displayed in the table
5. Correct count of items in the table should be displayed in the top left corner
6. These changes should also persist when navigating to and from the page

### CODE REVIEW

**Review by Nizar-Rahme — APPROVED** [review]
It looks good to me, though it would be better if it gets another approval since it's a quite big of a change.

**Comment by santtul** [comment]
Could you rebase this branch?

**Comment by santtul** [comment]
Screenshot 2020-10-30 at 14 50 21
Could we avoid the scrollbar in this dropdown?

**Comment by santtul** [comment]
The created browser tests seems to fail like this:
```yarn browser-test:local```
```
 List view table state persistence
 ✖ Application list

   1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

       > | Selector('div[class^="table_tableWrapper"]')
         |   .find('div[class^="table_headerCell"]')
         |   .nth(3)
         |   .child('div[class^="table_sortArrowWrapper"]')
```

**Comment by ahie** [comment]
> The created browser tests seems to fail like this:
> `yarn browser-test:local`
> 
> ```
>  List view table state persistence
>  ✖ Application list
> 
>    1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.
> 
>        > | Selector('div[class^="table_tableWrapper"]')
>          |   .find('div[class^="table_headerCell"]')
>          |   .nth(3)
>          |   .child('div[class^="table_sortArrowWrapper"]')
> ```

Likely caused by the changes to default sorting order. Will take a look.

**Review by santtul — CHANGES_REQUESTED** [review]
Great work! 🎖️  Just couple of comments.

**Comment by ahie** [comment]
> > The created browser tests seems to fail like this:
> > `yarn browser-test:local`
> > ```
> >  List view table state persistence
> >  ✖ Application list
> > 
> >    1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.
> > 
> >        > | Selector('div[class^="table_tableWrapper"]')
> >          |   .find('div[class^="table_headerCell"]')
> >          |   .nth(3)
> >          |   .child('div[class^="table_sortArrowWrapper"]')
> > ```
> 
> Likely caused by the changes to default sorting order. Will take a look.

Looks like a new column has been added to the table, so fixed the test to sort the correct column.

**Comment by ahie** [comment]
> Screenshot 2020-10-30 at 14 50 21
> Could we avoid the scrollbar in this dropdown?

Made all options visible.

**Review by santtul — APPROVED** [review]

**Pull request merged**
